services:
  aeternum-server:
    container_name: aeternum-api
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - 8080:8080
  aeternum-cli:
    container_name: aeternum-cli
    build:
      context: .
      dockerfile: docker/cli.Dockerfile
    ports:
      - 8080:8080
  aeternum-docs:
    container_name: aeternum-docs
    build:
      context: .
      dockerfile: docs/Dockerfile
    ports:
      - 8000:8000
