site_name: Aeternum API
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # Light Mode
    scheme: default
    toggle:
      icon: material/weather-night
      name: Light
    primary: red
    accent: deep orange
  nav:
    - Home: index.md
    - Usage Guide: usage/api.md
  features:
    - navigation.instant
    - search.highlight
    - content.code.annotate
  nav_style: primary
  highlightjs: true
  hljs_languages:
    - yaml
    - json
    - go
    - bash
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences # Enables syntax highlighting for code blocks
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.emoji
  - pymdownx.tabbed:
      alternate_style: true # Enables tabbed code sections
extra_css:
  - styles/custom.css
copyright: Copyright &copy; 2025 Joaquin Franco
