---
name: "Create Snap release"
description: "Publish the release via Snapcraft"

runs:
  using: composite
  steps:
    - name: Set up Golang
      uses: actions/setup-go@v5
      with:
        go-version: "1.22"

    - name: Install dependencies
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y snapcraft

    - name: Install dependencies
      shell: bash
      run: |
        file ./aeternum
        cd build/snap
        snapcraft --destructive-mode
