name: Deployment

on:
  push:
    branches:
      - "main"
    paths:
      - "**.go"
      - "specs.json"
      - "Dockerfile"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install Just
        uses: extractions/setup-just@v2

      - name: Install modules
        run: |
          just tidy

      - name: Run tests
        run: |
          just test

  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main'}}
    environment: production
    needs: build

    steps:
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
            curl -s ${{ secrets.RENDER_DEPLOY_HOOK }} \
            -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY"
