name: Smoke Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # Every hour

env:
  API_BASE_URL: https://aeternum-api.onrender.com

jobs:
  smoke-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Run smoke tests
        env:
          API_BASE_URL: ${{ env.API_BASE_URL }}
        run: |
          go run external-tests/smoke/main.go
