name: Smoke Tests

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: "0 */2 * * *" # Every 2 hours

jobs:
  smoke-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build Smoke Test Runner
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
        run: |
          go run external-tests/smoke/main.go
