name: CI Testing

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.22"

    - name: Install Just
      uses: extractions/setup-just@v2

    - name: Install modules
      run: |
        just tidy

    - name: Run tests
      run: |
        just test
